compile:


measure:
	sudo modprobe msr
	sudo ../../RAPL/main "/usr/local/src/vw8.1.1pul/bin/linuxx86_64/vwlinuxx86_64 /usr/local/src/vw8.1.1pul/image/benchmarks.im -nogui -evaluate \"Tests mandelbrot2\" -a 16000" Smalltalk mandelbrot

run:
	/usr/local/src/vw8.1.1pul/bin/linuxx86_64/vwlinuxx86_64 /usr/local/src/vw8.1.1pul/image/benchmarks.im -nogui -evaluate \"Tests mandelbrot2\" -a 16000