name: Docker

on:
  push:
    branches: ["master"]
    paths:
     - "docker/**"
     - ".github/workflows/docker.yml"
  pull_request:
    branches: ["master"]
    paths:
     - "docker/**"
     - ".github/workflows/docker.yml"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: sudo docker build -f $GITHUB_WORKSPACE/docker/main.Dockerfile -t energy-languages $GITHUB_WORKSPACE
